src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="json_array", nullable=true)
     */
    private $keyword;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $contents;

    /**
     * @ORM\Column(type="datetime")
     */
    private $pulic_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_show;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="articles",fetch="EAGER")
     */
    private $categories;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $this->CloseTags($this->contents);
        return $this;
    }

    public function getKeyword()
    {
        return $this->keyword;
    }

    public function setKeyword($keyword): self
    {
        $this->keyword = $keyword;

        return $this;
    }

    public function getContents(): ?string
    {
        return $this->contents;
    }

    public function setContents(?string $contents): self
    {
        $this->description = $this->CloseTags($contents);
        $this->contents = $contents;

        return $this;
    }

    public function getPulicAt(): ?\DateTimeInterface
    {
        return $this->pulic_at;
    }

    public function setPulicAt(\DateTimeInterface $pulic_at): self
    {
        $this->pulic_at = $pulic_at;

        return $this;
    }

    public function getIsShow(): ?bool
    {
        return $this->is_show;
    }

    public function setIsShow(bool $is_show): self
    {
        $this->is_show = $is_show;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
        }

        return $this;
    }


    function CloseTags($html) {
        // 直接过滤错误的标签 <[^>]的含义是 匹配只有<而没有>的标签
        // 而preg_replace会把匹配到的用''进行替换
        $html = preg_replace('/<[^>]*$/','',$html);

        // 匹配开始标签，这里添加了1-6，是为了匹配h1~h6标签
        preg_match_all('#<([a-z1-6]+)(?: .*)?(?<![/|/ ])>#iU', $html, $result);
        $opentags = $result[1];
        // 匹配结束标签
        preg_match_all('#</([a-z1-6]+)>#iU', $html, $result);
        $closetags = $result[1];
        $len_opened = count($opentags);
        // 如何两种标签数目一致 说明截取正好
        if (count($closetags) == $len_opened) { return $html; }

        $opentags = array_reverse($opentags);
        // 过滤自闭和标签，也可以在正则中过滤 <(?!meta|img|br|hr|input)>
        $sc = array('br','input','img','hr','meta','link');

        for ($i=0; $i < $len_opened; $i++) {
            $ot = strtolower($opentags[$i]);
            if (!in_array($opentags[$i], $closetags) && !in_array($ot,$sc)) {
                $html .= '</'.$opentags[$i].'>';
            } else {
                unset($closetags[array_search($opentags[$i], $closetags)]);
            }
        }
        return $html;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Category;
use Doctrine\ORM\EntityRepository;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',TextType::class,[
                'label' => 'article.title',
            ])
            ->add('keyword',TextType::class,[
                'label' => 'article.keyword',
            ])
            ->add('contents',CKEditorType::class,[
                'label' => 'article.contents',
                'config' => ['my_config'],
                'attr' => ['class' => 'tui-editor'],
            ])
            ->add('pulic_at',DateTimeType::class,[
                'label' => 'article.pulic_at',
            ])
            ->add('is_show',CheckboxType::class,[
                'label' => 'article.is_show',
                'attr' => ['class' => 'checkbox']
            ])
            ->add('categories', EntityType::class, [
                'label' => 'article.categories',
                'attr' => array('multiple' => 'multiple'),
                'class'         => Category::class,
                'choice_label'  => function ($categories) {
                    return $categories->getName();
                },
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('c')
                        ->andWhere('c.is_public = true');
                },
                'multiple'      => true,
            ])

            ->add('save',SubmitType::class,[
                'label' => 'article.save',
                'attr' => [
                    'class' => 'btn btn-primary'
                ],
            ])
            ->getForm();
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }

    function CloseTags($html) {
        // 直接过滤错误的标签 <[^>]的含义是 匹配只有<而没有>的标签
        // 而preg_replace会把匹配到的用''进行替换
        $html = preg_replace('/<[^>]*$/','',$html);

        // 匹配开始标签，这里添加了1-6，是为了匹配h1~h6标签
        preg_match_all('#<([a-z1-6]+)(?: .*)?(?<![/|/ ])>#iU', $html, $result);
        $opentags = $result[1];
        // 匹配结束标签
        preg_match_all('#</([a-z1-6]+)>#iU', $html, $result);
        $closetags = $result[1];
        $len_opened = count($opentags);
        // 如何两种标签数目一致 说明截取正好
        if (count($closetags) == $len_opened) { return $html; }

        $opentags = array_reverse($opentags);
        // 过滤自闭和标签，也可以在正则中过滤 <(?!meta|img|br|hr|input)>
        $sc = array('br','input','img','hr','meta','link');

        for ($i=0; $i < $len_opened; $i++) {
            $ot = strtolower($opentags[$i]);
            if (!in_array($opentags[$i], $closetags) && !in_array($ot,$sc)) {
                $html .= '</'.$opentags[$i].'>';
            } else {
                unset($closetags[array_search($opentags[$i], $closetags)]);
            }
        }
        return $html;
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use App\Repository\CategoryRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/article")
 */
class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="sb.article.index", methods="GET")
     */
    public function index(ArticleRepository $articleRepository,CategoryRepository $categoryRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $search = $request->query->all();
        $categories = $categoryRepository->getCategoies()->getQuery()->getResult();
        $articles =  $articleRepository->getArticles($search);
        $pagination = $paginator->paginate(
            $articles,
            $search['page'] ?? 1,
            10
        );
        return $this->render('sb/article/index.html.twig', [
            'pagination' => $pagination,
            'categories' => $categories,
            'search' => $search
        ]);
    }

    /**
     * @Route("/new", name="sb.article.new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($article);
            $em->flush();

            return $this->redirectToRoute('sb.article.index');
        }

        return $this->render('sb/article/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/show", name="sb.article.show", methods="GET")
     */
    public function show(Article $article): Response
    {
        return $this->render('sb/article/show.html.twig', ['info' => $article]);
    }

    /**
     * @Route("/{id}/edit", name="sb.article.edit", methods="GET|POST")
     */
    public function edit(Request $request, Article $article): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('sb.article.index', ['id' => $article->getId()]);
        }

        return $this->render('sb/article/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/delete", name="sb.article.delete", methods="DELETE")
     */
    public function delete(Request $request, Article $article): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($article);
            $em->flush();
        }

        return $this->redirectToRoute('sb.article.index');
    }
}

templates/sb/article/_delete_form.html.twig
<form method="post" action="{{ path('sb.article.delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <div class="form-group">
        <button id="article_save" name="article[save]" class="btn btn-danger">删除</button>
    </div>
</form>

templates/sb/article/edit.html.twig
{% extends 'sb/layout.html.twig' %}

{% block title %}{{ article.title ?? ''  }}{% endblock %}
{% block nav_name %}{{ article.title ?? '' }}{% endblock %}
{% block main %}
    {{ include('sb/article/_form.html.twig') }}
    {{ include('sb/article/_delete_form.html.twig') }}
{% endblock %}


{% block js %}
{% endblock %}

templates/sb/article/index.html.twig
{% extends 'sb/layout.html.twig' %}

{% block title %}Articles{% endblock %}
{% block nav_name %}Articles{% endblock %}
{% block main %}

<div class="searchbox panel-body">
    <div class="search_btbox"><span>快捷搜索</span></div>
    <form class="form-inline"  method="get" action="">
        <div class="form-group">
            <select id="category_id" name="category_id" class="form-control" data-placeholder="category/all">
                <option value="">category/all</option>
                {% for category in categories %}
                    <option value="{{  category.id ?? 0 }}" {% if search.category_id is defined and search.category_id  ==  category.id  %} selected {% endif %}>{{  category.name ?? '' }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
        <button type="submit" class="btn btn-primary ml-1">search</button>
        </div>
    </form>
</div>
<div class="panel">
<div class="panel-body panel-default">
    <div  class="table-responsive">
        <table width="100%" class="table table-striped">
            <thead>
            <tr>
                <th>{{ knp_pagination_sortable(pagination, 'Id', 'id') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Title', 'title') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Categories', 'categories') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'isShow', 'isShow') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'PubicAt', 'pubicAt') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'CreatedAt', 'createdAt') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'UpdatedAt', 'updatedAt') }}</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for article in pagination %}
                <tr>
                    <td>{{ article.id }}</td>
                    <td>{{ article.title }}</td>
                    <td>
                        {% for category in article.categories %}
                            <a href="#"><span>{{ category.name ?? '' }}</span></a>
                        {% endfor %}

                    </td>
                    <td>{{ article.isShow ? 'Yes' : 'No' }}</td>
                    <td>{{ article.pulicAt ? article.pulicAt|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ article.createdAt ? article.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ article.updatedAt ? article.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                    <td>

                        <div class="btn-group">
                            <button type="button" class="btn btn-warning btn-xs dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                Action
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu pull-right" role="menu">
                                <li> <a href="{{ path('sb.article.show', {'id': article.id}) }}">Show</a>
                                </li>
                                <li><a href="{{ path('sb.article.edit', {'id': article.id}) }}">Edit</a>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {{ knp_pagination_render(pagination) }}
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/sb/article/new.html.twig
{% extends 'sb/layout.html.twig' %}

{% block title %}Create Article{% endblock %}
{% block nav_name %}Create Article{% endblock %}
{% block main %}
    {{ include('sb/article/_form.html.twig') }}
    {#<a href="{{ path('article.index') }}">back to list</a>#}
{% endblock %}


{% block js %}
{% endblock %}

templates/sb/article/show.html.twig
{% extends 'sb/layout.html.twig' %}

{% block title %}{{ info.title ?? '' }}{% endblock %}
{% block nav_name %}{{ info.title ?? '' }}{% endblock %}
{% block main %}
    <div class="panel-body">
        {% autoescape false %}
            {{ info.contents ?? ''  }}
        {% endautoescape %}

        <p class="text-right">公开时间：{{ (info.pubicAt ?? '') |date("Y-m-d H:i:s") }}</p>
        <p class="text-right">创建时间：{{ (info.createdAt ?? '') |date("Y-m-d H:i:s") }}</p>
        <p class="text-right">上次更新时间：{{ (info.updatedAt ?? '') |date("Y-m-d H:i:s") }}</p>
    </div>
{% endblock %}

{% block js %}
{% endblock %}